### ISSUE TITLE
New install: sndfile library not found

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/AutoEq#100]
Trying to get AutoEQ on my desktop, worked fine on my laptop. Getting the error below.

Searched my drive for the libsndfile64bit.dll and it was also in the Impulcifer folder. Copied that across to the site-packages folder and AutoEQ runs help fine now. But probably something missing in the requirements package?

The help commands executes fine but when I try and actually run a few commands I still get errors.

```
(venv) C:\Users\dushy\AutoEq>python frequency_response.py -h
Traceback (most recent call last):
  File "C:\Users\dushy\AutoEq\venv\lib\site-packages\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frequency_response.py", line 13, in <module>
    import soundfile as sf
  File "C:\Users\dushy\AutoEq\venv\lib\site-packages\soundfile.py", line 163, in <module>
    _path, '_soundfile_data', _libname))
OSError: cannot load library 'C:\Users\dushy\AutoEq\venv\lib\site-packages\_soundfile_data\libsndfile64bit.dll': error 0x7e
```

The error I get when I run a command after manually copying over

```
(venv) C:\Users\dushy\AutoEq>python frequency_response.py --input_dir="oratory1990\data\inear\Sony WF-1000XM3" --output_dir="my_results/Bose 700 (WF-1000XM3 o90)" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="results\oratory1990\harman_over-ear_2018\Bose Headphone 700\Bose Headphone 700.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4
Traceback (most recent call last):
  File "frequency_response.py", line 1861, in <module>
    FrequencyResponse.main(**FrequencyResponse.cli_args())
  File "frequency_response.py", line 1718, in main
    bit_depth
  File "C:\Users\dushy\AutoEq\venv\lib\site-packages\soundfile.py", line 315, in write
    subtype, endian, format, closefd) as f:
  File "C:\Users\dushy\AutoEq\venv\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\dushy\AutoEq\venv\lib\site-packages\soundfile.py", line 1172, in _open
    openfunction = _snd.sf_wchar_open
AttributeError: cffi library 'C:\Users\dushy\AutoEq\venv\lib\site-packages\_soundfile_data\libsndfile64bit.dll' has no function, constant or global variable named 'sf_wchar_open'
```

**Comment by jaakkopasanen** [comment]
Definitely something going on here. Someone reported the same thing in the Impulcifer thread. Maybe there's a new version of Python or soundfile package which breaks the compatibility. Or maybe some Windowses don't have the right DLL installed.

The way these dependencies work is that every package declares it's own dependencies so everything needed should be automatically installed.

Could you try to install AutoEQ in a different location on your laptop? Just don't remove the old installation. Which versions of Python you have installed on both systems?

**Comment by rpx91** [comment]
Yep - will try tomorrow and report back.

**Comment by rpx91** [comment]
New install on my laptop isn't working either. The old install works fine.

Python on my laptop

`Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32`

Python on desktop

`Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32`

Wonder if this is related to my issues with plots. But those work on my desktop but not laptop.

**Comment by jaakkopasanen** [comment]
Alright, this means the culprit isn't Python or Windows. Main suspect is soundfile package itself.

Could you check which version of soundfile you have installed in the Impulcifer which works on your laptop? And then the same for the new installation.
```
python -c 'import soundfile; print(soundfile.__version__)'
```

You can fix the soundfile version by changing the line in requirements.txt from
```
soundfile~=0.10.2
```
to
```
soundfile==0.10.2
```
and then you have to install dependencies again with `-U` flag
```
pip install -U -r requirements.txt
```

**Comment by rpx91** [comment]
I get an error when trying to run the first command

```
C:\Users\dushy\Impulcifer>python -c 'import soundfile; print(soundfile.__version__)'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
```

**Comment by jaakkopasanen** [comment]
Sorry it should have been: `python -c "import soundfile; print(soundfile.__version__)"`

I could not reproduce this on my own PC so I really hope you could help me with this one.

**Comment by jaakkopasanen** [comment]
Soundfile version 0.10.3 was released two days ago and yesterday people started to have problems with it...

**Comment by rpx91** [comment]
So when I run `python -c "import soundfile; print(soundfile.__version__)"` in the venv environment it doesn't report anything. I get the below error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'soundfile'

However, when I run it just without the virtual environment. Just from the command line I get the following:

`0.10.2`

```

Happy to help :) Impulcifer has changed my (audiophile) life!

**Comment by jaakkopasanen** [comment]
Sounds like you ran `pip install -r requirements.txt` while not having virtual environment activated. The packages from requirements don't end up system level when installing then during virtual environment session.

Could you try again? Make sure you have the correct virtual environment activated and have installed requirements there. If you switch from the old installation folder to the new the virtual environment doesn't change. You have to run
```
deactivate
```
and then activate the virtual environment in the new folder
```
venv\Scripts\activate
```
Now if `python -c "import soundfile; print(soundfile.__version__)"` says soundfile not found, you need to install it
```
pip install -U -r requirements.txt
```
and try again: `python -c "import soundfile; print(soundfile.__version__)"`

**Comment by rpx91** [comment]
OK - so now the new installation also works on my laptop. I did make a mistake in the install instructions.

I shall try and get it working on my desktop also and report back :)

**Comment by rpx91** [comment]
I can confirm it's now working on my desktop, user error. Apologies!

**Comment by jaakkopasanen** [comment]
Could you give a description what did you do and what went wrong? I'd like to be able to assist other users who experience similar problems.

**Comment by rpx91** [comment]
I just deleted the venv folder in AutoEQ and refollowed your instructions from. You have to make sure you exit the terminal window otherwise you'll get a file lock.

I then just followed the install instructions again from "create virtual environment"

**Comment by shaevitz** [comment]
I am also having this problem. MacBook Pro. Python 3.6.7. The virtualenv works and the pip install goes through without any errors, but when I run autoeq.py I get:
```
(venv) (base) $ python autoeq.py --help
Traceback (most recent call last):
  File "autoeq.py", line 6, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'
```
The same thing happens if I just try to import sound file in python. 

Below is the output of the pip install:
```
(venv) (base) $ pip install -U -r requirements.txt
Collecting Pillow~=7.2.0
  Using cached Pillow-7.2.0-cp37-cp37m-macosx_10_10_x86_64.whl (2.2 MB)
Collecting matplotlib~=3.1.1
  Using cached matplotlib-3.1.3-cp37-cp37m-macosx_10_9_x86_64.whl (13.2 MB)
Collecting pandas~=0.25.1
  Using cached pandas-0.25.3-cp37-cp37m-macosx_10_9_x86_64.whl (10.2 MB)
Collecting scipy~=1.3.1
  Using cached scipy-1.3.3-cp37-cp37m-macosx_10_6_intel.whl (27.7 MB)
Collecting numpy~=1.17.2
  Using cached numpy-1.17.5-cp37-cp37m-macosx_10_9_x86_64.whl (15.1 MB)
Collecting tensorflow~=2.0.0
  Using cached tensorflow-2.0.3-cp37-cp37m-macosx_10_9_x86_64.whl (102.7 MB)
Collecting tabulate~=0.8.5
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting soundfile==0.10.2
  Using cached SoundFile-0.10.2-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl (616 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.0-cp37-cp37m-macosx_10_9_x86_64.whl (61 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting keras-applications>=1.0.8
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Collecting absl-py>=0.7.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting google-pasta>=0.1.6
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting tensorflow-estimator<2.1.0,>=2.0.0
  Using cached tensorflow_estimator-2.0.1-py2.py3-none-any.whl (449 kB)
Processing /Users/jshaevitz/Library/Caches/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6/termcolor-1.1.0-cp37-none-any.whl
Processing /Users/jshaevitz/Library/Caches/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6/wrapt-1.12.1-cp37-cp37m-macosx_10_7_x86_64.whl
Collecting tensorboard<2.1.0,>=2.0.0
  Using cached tensorboard-2.0.2-py3-none-any.whl (3.8 MB)
Collecting keras-preprocessing>=1.0.5
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting protobuf>=3.6.1
  Using cached protobuf-3.13.0-cp37-cp37m-macosx_10_9_x86_64.whl (1.3 MB)
Collecting astor>=0.6.0
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting grpcio>=1.8.6
  Using cached grpcio-1.33.2-cp37-cp37m-macosx_10_9_x86_64.whl (3.4 MB)
Processing /Users/jshaevitz/Library/Caches/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd/gast-0.2.2-cp37-none-any.whl
Requirement already satisfied, skipping upgrade: wheel>=0.26; python_version >= "3" in ./venv/lib/python3.7/site-packages (from tensorflow~=2.0.0->-r requirements.txt (line 6)) (0.34.2)
Collecting cffi>=1.0
  Using cached cffi-1.14.3-2-cp37-cp37m-macosx_10_9_x86_64.whl (176 kB)
Collecting h5py
  Using cached h5py-2.10.0-cp37-cp37m-macosx_10_6_intel.whl (3.0 MB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied, skipping upgrade: setuptools>=41.0.0 in ./venv/lib/python3.7/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow~=2.0.0->-r requirements.txt (line 6)) (46.1.3)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.3-py3-none-any.whl (96 kB)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.23.0-py2.py3-none-any.whl (114 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.5"
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Installing collected packages: Pillow, six, cycler, numpy, pyparsing, kiwisolver, python-dateutil, matplotlib, pytz, pandas, scipy, h5py, keras-applications, absl-py, google-pasta, opt-einsum, tensorflow-estimator, termcolor, wrapt, werkzeug, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, chardet, certifi, urllib3, idna, requests, oauthlib, requests-oauthlib, google-auth-oauthlib, grpcio, protobuf, zipp, importlib-metadata, markdown, tensorboard, keras-preprocessing, astor, gast, tensorflow, tabulate, pycparser, cffi, soundfile
Successfully installed Pillow-7.2.0 absl-py-0.11.0 astor-0.8.1 cachetools-4.1.1 certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cycler-0.10.0 gast-0.2.2 google-auth-1.23.0 google-auth-oauthlib-0.4.2 google-pasta-0.2.0 grpcio-1.33.2 h5py-2.10.0 idna-2.10 importlib-metadata-2.0.0 keras-applications-1.0.8 keras-preprocessing-1.1.2 kiwisolver-1.3.0 markdown-3.3.3 matplotlib-3.1.3 numpy-1.17.5 oauthlib-3.1.0 opt-einsum-3.3.0 pandas-0.25.3 protobuf-3.13.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 requests-oauthlib-1.3.0 rsa-4.6 scipy-1.3.3 six-1.15.0 soundfile-0.10.2 tabulate-0.8.7 tensorboard-2.0.2 tensorflow-2.0.3 tensorflow-estimator-2.0.1 termcolor-1.1.0 urllib3-1.25.11 werkzeug-1.0.1 wrapt-1.12.1 zipp-3.4.0


```
