### ISSUE TITLE
Error downloading measures

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jaakkopasanen/AutoEq#133]
Command and results:
```
(venv) C:\AutoEq-master>python measurements/update_measurements.py
Traceback (most recent call last):
  File "measurements/update_measurements.py", line 19, in <module>
    main()
  File "measurements/update_measurements.py", line 13, in main
    crawler = cls()
  File "C:\AutoEq-master\measurements\crawler.py", line 16, in __init__
    self.links = self.get_links()
  File "C:\AutoEq-master\measurements\oratory1990\oratory1990_crawler.py", line 45, in get_links
    raise RedditCrawlFailed('Could not read data in Reddit. Open reddit.html in browser and re-run!')
measurements.oratory1990.oratory1990_crawler.RedditCrawlFailed: Could not read data in Reddit. Open reddit.html in browser and re-run!
```

And open `reddit.html` in browser shows:
```
Something went wrong;


                  ,d"=≥,.,qOp,
                 ,7'  ''²$(  )
                ,7'      '?q$7'
             ..,$$,.
   ,.  .,,--***²""²***--,,.  .,
 ²   ,p²''              ''²q,   ²
:  ,7'                      '7,  :
 ' $      ,db,      ,db,      $ '
  '$      ²$$²      ²$$²      $'    Using Reddit at work? Work for Reddit.
  '$                          $'        https://www.reddit.com/jobs
   '$.     .,        ,.     .$'
    'b,     '²«»«»«»²'     ,d'
     '²?bn,,          ,,nd?²'
       ,7$ ''²²²²²²²²'' $7,
     ,² ²$              $² ²,
     $  :$              $:  $
     $   $              $   $
     'b  q:            :p  d'
      '²«?$.          .$?»²'
         'b            d'
       ,²²'?,.      .,?'²²,
      ²==--≥²²==--==²²≤--==²
index.ts:5:10
Starting Raven release 52dcf9e-production public url https://6b5ce051b2ed4032bd906af3de0630cd@oops.redditmedia.com/11 index.tsx:161:10
Loading failed for the <script> with source “file:///tag/js/gpt.js”. reddit.html:1:1
Loading failed for the <script> with source “file:///aax2/apstag.js”. reddit.html:1:1
Loading failed for the <script> with source “file:///aax.js?pub=AAX763KC6&hst=&ver=1.2”. reddit.html:1:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///errors. (Reason: CORS request not http).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gateway.reddit.com/desktopapi/v1/subreddits/oratory1…de=structuredStyles%2CprefsSubreddit&sort=hot&layout=classic. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gateway.reddit.com/desktopapi/v1/subreddits/oratory1…de=structuredStyles%2CprefsSubreddit&sort=hot&layout=classic. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gql.reddit.com/?request_timestamp=1583145224591. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gql.reddit.com/?request_timestamp=1583145224591. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oops.redditmedia.com/api/11/store/?sentry_key=6b5ce051b2ed4032bd906af3de0630cd&sentry_version=7. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.reddit.com/api/jail/asknicely.json?feature=&app_name=web2x&raw_json=1&gilding_detail=1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.reddit.com/api/jail/asknicely.json?feature=&app_name=web2x&raw_json=1&gilding_detail=1. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.reddit.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by mhtvsSFrpHdE** [comment]
The page doesn't show a list about data, it's just keep blank and pop up error hint.  
`Something went wrong`

**Comment by jaakkopasanen** [comment]
This happens to me but it the download script seems to work for me after I open the reddit.html file in browser. So
1. Run script and get an error
2. Open reddit.html in browser and get an empty page
3. Run script again and get the data successfully

I do admit that this might not work always and for everyone but I personally got it working like this at least a few times. I need to do something else for Reference Audio Analyzer because that requires running Javascript to get the page rendered. Maybe I separate the html doc download and the parsing or use a headless chrome.

**Comment by jaakkopasanen** [comment]
This is fixed now. I started using headless Chrome with Selenium for crawling oratory1990 results. Chrome needs to be installed on the system and measurements folder needs chromedriver binary.
