### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy._lib'

### ISSUE THREAD

**Issue by NekoAlosama** [jaakkopasanen/AutoEq#171]
I am using my AutoEq-optimized fork for this example, but it should share the code of the normal repo.
```
Traceback (most recent call last):
  File "results\update_results.py", line 7, in <module>
    from autoeq import batch_processing
  File "C:\*\AutoEq-optimized\autoeq.py", line 12, in <module>
    from frequency_response import FrequencyResponse
  File "C:\*\AutoEq-optimized\frequency_response.py", line 9, in <module>
    from scipy.interpolate import InterpolatedUnivariateSpline
  File "C:\*\AppData\Roaming\Python\Python37\site-packages\scipy\__init__.py", line 110, in <module>
    from scipy._lib._version import NumpyVersion as _NumpyVersion
ModuleNotFoundError: No module named 'scipy._lib'
```
I have my modules updated to the version in requirements.txt.

**Comment by NekoAlosama** [comment]
@jaakkopasanen

**Comment by NekoAlosama** [comment]
I can confirm that this is happening on the regular repo and not affected by my fork.

**Comment by NekoAlosama** [comment]
Nevermind, probably an error on my end because of the last line.

**Comment by NekoAlosama** [comment]
Opening this back up because idk how you got past this @jaakkopasanen

**Comment by NekoAlosama** [comment]
Fixed with --force-reinstall, --user, --no-cache-dir, etc
