### ISSUE TITLE
AutoEq fails with "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by mikidep** [jaakkopasanen/AutoEq#174]
I am using it on macOS Catalina and Python 3.7.3. The full command I used is:
```
python autoeq.py --input_dir my_measurements/samson-850s --output_dir my_results/samson-850s --compensation compensation/zero.csv --equalize --parametric_eq --max_filters 4
```

and here is the full stack trace:

```
Traceback (most recent call last):
  File "autoeq.py", line 303, in <module>
    batch_processing(**cli_args())
  File "autoeq.py", line 103, in batch_processing
    fs=fs[0] if type(fs) == list else fs
  File "/Users/mikidep/AutoEq/frequency_response.py", line 1656, in process
    peq_filters, n_peq_filters, peq_max_gains = self.optimize_parametric_eq(max_filters=max_filters, fs=fs)
  File "/Users/mikidep/AutoEq/frequency_response.py", line 630, in optimize_parametric_eq
    fs=fs
  File "/Users/mikidep/AutoEq/frequency_response.py", line 278, in optimize_biquad_filters
    import tensorflow.compat.v1 as tf
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Users/mikidep/AutoEq/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration
```

I am also attaching the measurements CSV (standardized by AutoEq):
[reference_curve.csv.txt](https://github.com/jaakkopasanen/AutoEq/files/4678282/reference_curve.csv.txt)

**Comment by jaakkopasanen** [comment]
Looks like there is bug in Tensorflow or Python itself on Catalina: https://github.com/tensorflow/serving/issues/1280

Did you just now install Python? If not, try upgrading to the latest 3.7.x version. If yes, try installing some older version of Python.

**Comment by jaakkopasanen** [comment]
I'm going to assume this is due to Python version on Catalina. Please reopen if this does not solve your problem.
