### ISSUE TITLE
pip install -r requirements.txt causes error On Windows 10

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#244]
I'm aware of #239 but not sure whether it applies. I'm on Windows 10 20H2. I'm following the install steps in README.md. Running "pip install -r requirements.txt" gives the following output:
```
Collecting Pillow~=7.2.0
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
Collecting matplotlib~=3.1.1
  Using cached matplotlib-3.1.3.tar.gz (40.9 MB)
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
    ERROR: Command errored out with exit status 1:
     command: 'h:\autoeq\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Barack Obama\\AppData\\Local\\Temp\\pip-install-4xw34rdi\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Barack Obama\\AppData\\Local\\Temp\\pip-install-4xw34rdi\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd'
         cwd: C:\Users\Barack Obama\AppData\Local\Temp\pip-install-4xw34rdi\matplotlib\
    Complete output (71 lines):
    WARNING: The wheel package is not available.
    ================================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
      matplotlib: yes [3.1.3]
          python: yes [3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC
                      v.1927 64 bit (AMD64)]]
        platform: yes [win32]

    OPTIONAL SUBPACKAGES
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
             agg: yes [installing]
           tkagg: yes [installing; run-time loading from Python Tcl/Tk]
          macosx: no  [Mac OS-X only]

    OPTIONAL PACKAGE DATA
            dlls: no  [skipping due to configuration]

    running egg_info
    creating C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info
    writing C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info\dependency_links.txt
    writing namespace_packages to C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info\namespace_packages.txt
    writing requirements to C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info\requires.txt
    writing top-level names to C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info\top_level.txt
    writing manifest file 'C:\Users\Barack Obama\AppData\Local\Temp\pip-pip-egg-info-4nx5kabd\matplotlib.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Barack Obama\AppData\Local\Temp\pip-install-4xw34rdi\matplotlib\setup.py", line 273, in <module>
        setup(
      File "h:\autoeq\venv\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\Python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files\Python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "h:\autoeq\venv\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
        self.find_sources()
      File "h:\autoeq\venv\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
        mm.run()
      File "h:\autoeq\venv\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
        self.add_defaults()
      File "h:\autoeq\venv\lib\site-packages\setuptools\command\egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "C:\Program Files\Python39\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Program Files\Python39\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Program Files\Python39\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Program Files\Python39\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\Barack Obama\AppData\Local\Temp\pip-install-4xw34rdi\matplotlib\setup.py", line 106, in finalize_options
        self.distribution.ext_modules[:] = filter(
      File "C:\Users\Barack Obama\AppData\Local\Temp\pip-install-4xw34rdi\matplotlib\setup.py", line 107, in <genexpr>
        None, (package.get_extension() for package in good_packages))
      File "C:\Users\Barack Obama\AppData\Local\Temp\pip-install-4xw34rdi\matplotlib\setupext.py", line 806, in get_extension
        Numpy().add_flags(ext)
      File "C:\Users\Barack Obama\AppData\Local\Temp\pip-install-4xw34rdi\matplotlib\setupext.py", line 607, in add_flags
        import numpy as np
      File "c:\users\barack obama\appdata\local\temp\pip-install-4xw34rdi\matplotlib\.eggs\numpy-1.19.4-py3.9-win-amd64.egg\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "c:\users\barack obama\appdata\local\temp\pip-install-4xw34rdi\matplotlib\.eggs\numpy-1.19.4-py3.9-win-amd64.egg\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('c:\\users\\barack obama\\appdata\\local\\temp\\pip-install-4xw34rdi\\matplotlib\\.eggs\\numpy-1.19.4-py3.9-win-amd64.egg\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the 'h:\autoeq\venv\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by jaakkopasanen** [comment]
Could you try again now? I've made some changes to the `requirements.txt`.

Get the latest
```
git pull
```

Try updating pip first:
```
python -m pip install -U pip
```

and then install dependencies
```
python -m pip install -U -r requirements.txt
```

**Comment by markanini** [comment]
I got the following output:
```
(venv) H:\AutoEq>python -m pip install -U -r requirements.txt
ERROR: Could not find a version that satisfies the requirement tensorflow<2.4.0,>=2.3.0
ERROR: No matching distribution found for tensorflow<2.4.0,>=2.3.0
```

**Comment by jaakkopasanen** [comment]
Which version of Python do you have?

**Comment by markanini** [comment]
Python v3.9.1 x64

**Comment by pranjalepeno** [comment]
I've been facing the same problem too

**Comment by jaakkopasanen** [comment]
@markanini could you try with Python 3.8?

**Comment by markanini** [comment]
Python 3.8.7 64-bit installed for all users works!
