### ISSUE TITLE
Error caused by referencing 'self' in a staticmethod

### ISSUE THREAD

**Issue by cpiscos** [jaakkopasanen/AutoEq#257]
'self' is being referenced in a static method causing an error preventing run.
https://github.com/jaakkopasanen/AutoEq/blob/0a32d03ea0c7e0680193841c19bc35f1de68ab56/frequency_response.py#L300

> Traceback (most recent call last):
  File "autoeq.py", line 318, in <module>
    batch_processing(**cli_args())
  File "autoeq.py", line 84, in batch_processing
    peq_filters, n_peq_filters, peq_max_gains, fbeq_filters, n_fbeq_filters, fbeq_max_gain = fr.process(
  File "C:\Users\Chris\AutoEq\frequency_response.py", line 1685, in process
    peq_filters, n_peq_filters, peq_max_gains = self.optimize_parametric_eq(max_filters=max_filters, fs=fs)
  File "C:\Users\Chris\AutoEq\frequency_response.py", line 626, in optimize_parametric_eq
    _eq, rmse, _fc, _Q, _gain, _coeffs_a, _coeffs_b = self.optimize_biquad_filters(
  File "C:\Users\Chris\AutoEq\frequency_response.py", line 300, in optimize_biquad_filters
    fr_target = self.__class__(name='Filter Initialization', frequency=frequency, raw=target)
NameError: name 'self' is not defined

**Comment by jaakkopasanen** [comment]
Oopsie daisy! That was not supposed to get committed. It's fixed now though.

Thanks for reporting!
