### ISSUE TITLE
Error with frequency_response.py

### ISSUE THREAD

**Issue by bunkbail** [jaakkopasanen/AutoEq#27]
I own an Onkyo A800 headphone and it doesn't being supported by AutoEQ. So I made a CSV file using WebPlotDigitizer, plotting the graph based on the frequency response I got from [here](https://cdn.head-fi.org/a/8996409.jpg). I made a header row consisting `frequency,raw` in said CSV file ([pastebin link here](https://pastebin.com/raw/Yg8iYyP3)), then put it into a new folder called `onkyo` inside the AutoEQ folder. I set up everything and I can't seem to make it work. I use the following line:

> python frequency_response.py --input_dir="onkyo" --compensation="headphonecom\resources\headphonecom_compensation_sbaf-serious.csv" --equalize --show_plot

And it then shows the following error:

> Traceback (most recent call last):
  File "frequency_response.py", line 1482, in <module>
    FrequencyResponse.main(**FrequencyResponse.cli_args())
  File "frequency_response.py", line 1435, in main
    treble_gain_k=treble_gain_k
  File "frequency_response.py", line 1299, in process
    self.interpolate()
  File "frequency_response.py", line 765, in interpolate
    interpolator = InterpolatedUnivariateSpline(np.log10(self.frequency), self.raw, k=pol_order)
  File "D:\AutoEq-master\venv\lib\site-packages\scipy\interpolate\fitpack2.py", line 601, in __init__
    raise ValueError('x must be strictly increasing')
ValueError: x must be strictly increasing

What did I do wrong here?

I use Python 3.6.8.

**Comment by bunkbail** [comment]
Thanks! That worked!
