### ISSUE TITLE
No crinacle results in ranking.md after importing raw data

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#285]
On Windows 10 64-bit I followed the instructions in measurements.md, copied the crinical raw data to the directories as instructed. Went on to run update_measurements.py and I'm not sure how to interpreted the output of the script other than no no dependencies are missing, I think:
`DevTools listening on ws://127.0.0.1:2265/devtools/browser/6cff16f4-5054-41b3-86b8-9f4ffd7a715a
Running CrinacleCrawler
"1 Plus X" is not known. Add true name and form to name index and run again.
"2HT" is not known. Add true name and form to name index and run again.
"4 Plus 2 Bass" is not known. Add true name and form to name index and run again.
"4 Plus 2 Norm" is not known. Add true name and form to name index and run again.
"4 Plus 2 Vokal" is not known. Add true name and form to name index and run again.
"A3000" is not known. Add true name and form to name index and run again.
"A4000" is not known. Add true name and form to name index and run again.
"Adonis" is not known. Add true name and form to name index and run again.
"Azul" is not known. Add true name and form to name index and run again.
"Bastille-R" is not known. Add true name and form to name index and run again.
"Bastille-V" is not known. Add true name and form to name index and run again.
"BD005 Pro" is not known. Add true name and form to name index and run again.
"Blessing 2 S2" is not known. Add true name and form to name index and run again.
"CE2" is not known. Add true name and form to name index and run again.
"CL2 S2" is not known. Add true name and form to name index and run again.
"CST" is not known. Add true name and form to name index and run again.
"Darling" is not known. Add true name and form to name index and run again.
"Dual Driver" is not known. Add true name and form to name index and run again.
"Dusk" is not known. Add true name and form to name index and run again.
"E4" is not known. Add true name and form to name index and run again.
"Electro" is not known. Add true name and form to name index and run again.
"Elixir" is not known. Add true name and form to name index and run again.
"FA9" is not known. Add true name and form to name index and run again.
"FD1" is not known. Add true name and form to name index and run again.
"FD5" is not known. Add true name and form to name index and run again.
"Flame" is not known. Add true name and form to name index and run again.
"Galaxy Buds Pro" is not known. Add true name and form to name index and run again.
"HE01" is not known. Add true name and form to name index and run again.
"IE300" is not known. Add true name and form to name index and run again.
"ION-4 Vietnam" is not known. Add true name and form to name index and run again.
"Janus" is not known. Add true name and form to name index and run again.
"Jasper" is not known. Add true name and form to name index and run again.
"L4 00" is not known. Add true name and form to name index and run again.
"L4 02" is not known. Add true name and form to name index and run again.
"L4 10" is not known. Add true name and form to name index and run again.
"L4 12" is not known. Add true name and form to name index and run again.
"Lola 2oclock" is not known. Add true name and form to name index and run again.
"Lola Max" is not known. Add true name and form to name index and run again.
"Lola Min" is not known. Add true name and form to name index and run again.
"Nanna 2.0" is not known. Add true name and form to name index and run again.
"Pink Lady S2" is not known. Add true name and form to name index and run again.
"Piston 1More" is not known. Add true name and form to name index and run again.
"RE2000" is not known. Add true name and form to name index and run again.
"RE800" is not known. Add true name and form to name index and run again.
"Roxanne 2 2oclock" is not known. Add true name and form to name index and run again.
"Roxanne 2 Max" is not known. Add true name and form to name index and run again.
"Roxanne 2 Min" is not known. Add true name and form to name index and run again.
"SA6" is not known. Add true name and form to name index and run again.
"SA6 On" is not known. Add true name and form to name index and run again.
"Sarda" is not known. Add true name and form to name index and run again.
"Semper Pink-pink" is not known. Add true name and form to name index and run again.
"Single Driver" is not known. Add true name and form to name index and run again.
"SSP" is not known. Add true name and form to name index and run again.
"Studio 3" is not known. Add true name and form to name index and run again.
"Studio 4" is not known. Add true name and form to name index and run again.
"T9iE" is not known. Add true name and form to name index and run again.
"UE4 Pro" is not known. Add true name and form to name index and run again.
"Versa" is not known. Add true name and form to name index and run again.
"Vesper S2" is not known. Add true name and form to name index and run again.
"VK4 S2" is not known. Add true name and form to name index and run again.
"Yao" is not known. Add true name and form to name index and run again.
"99 Neo" is not known. Add true name and form to name index and run again.
"AB-1266 Phi CC" is not known. Add true name and form to name index and run again.
"AB-1266 Phi" is not known. Add true name and form to name index and run again.
"Aeon 2 Noire" is not known. Add true name and form to name index and run again.
"Celestee" is not known. Add true name and form to name index and run again.
"Clear (Mg pads)" is not known. Add true name and form to name index and run again.
"Clear Mg" is not known. Add true name and form to name index and run again.
"Diana Phi" is not known. Add true name and form to name index and run again.
"Diana V2" is not known. Add true name and form to name index and run again.
"Edition X V2" is not known. Add true name and form to name index and run again.
"GL2000 (double) (leather)" is not known. Add true name and form to name index and run again.
"GL2000 (double) (perf hybrid)" is not known. Add true name and form to name index and run again.
"HE-1 (fresh pads)" is not known. Add true name and form to name index and run again.
"HE560 V1 S2" is not known. Add true name and form to name index and run again.
"HE6se" is not known. Add true name and form to name index and run again.
"Hive" is not known. Add true name and form to name index and run again.
"HP-300" is not known. Add true name and form to name index and run again.
"HP-50S" is not known. Add true name and form to name index and run again.
"Jade II" is not known. Add true name and form to name index and run again.
"LCD-GX" is not known. Add true name and form to name index and run again.
"Monitor 10" is not known. Add true name and form to name index and run again.
"Phoenix" is not known. Add true name and form to name index and run again.
"PM-3" is not known. Add true name and form to name index and run again.
"Shangri-La Jr" is not known. Add true name and form to name index and run again.
"Susvara" is not known. Add true name and form to name index and run again.
"TH500 (worn pads)" is not known. Add true name and form to name index and run again.
"TH610" is not known. Add true name and form to name index and run again.
"TH7" is not known. Add true name and form to name index and run again.
"TH900" is not known. Add true name and form to name index and run again.
"TH909" is not known. Add true name and form to name index and run again.
"TR-80" is not known. Add true name and form to name index and run again.
"Utopia S3" is not known. Add true name and form to name index and run again.
Running Oratory1990Crawler
[0330/194900.225:INFO:CONSOLE(1)] "
                  ,d"=ΓëÑ,.,qOp,
                 ,7'  ''┬▓$(  )
                ,7'      '?q$7'
             ..,$$,.
   ,.  .,,--***┬▓""┬▓***--,,.  .,
 ┬▓   ,p┬▓''              ''┬▓q,   ┬▓
:  ,7'                      '7,  :
 ' $      ,db,      ,db,      $ '
  '$      ┬▓$$┬▓      ┬▓$$┬▓      $'    Using Reddit at work? Work for Reddit.
  '$                          $'      https://www.redditinc.com/careers
   '$.     .,        ,.     .$'
    'b,     '┬▓┬½┬╗┬½┬╗┬½┬╗┬▓'     ,d'
     '┬▓?bn,,          ,,nd?┬▓'
       ,7$ ''┬▓┬▓┬▓┬▓┬▓┬▓┬▓┬▓'' $7,
     ,┬▓ ┬▓$              $┬▓ ┬▓,
     $  :$              $:  $
     $   $              $   $
     'b  q:            :p  d'
      '┬▓┬½?$.          .$?┬╗┬▓'
         'b            d'
       ,┬▓┬▓'?,.      .,?'┬▓┬▓,
      ┬▓==--ΓëÑ┬▓┬▓==--==┬▓┬▓Γëñ--==┬▓
", source: https://www.redditstatic.com/desktop2x/Chat~Governance~Reddit.f5769ee3503ebea4e475.js (1)
[0330/194900.477:INFO:CONSOLE(1)] "%cStarting Raven %crelease %c73c1163859af88bce0d58e22497737a6c30e541c-production %cpublic url %chttps://6b5ce051b2ed4032bd906af3de0630cd@oops.redditmedia.com/11 color: #7E53C1 color: #7E53C1 color: #FFB000 color: #7E53C1 color: #FFB000", source: https://www.redditstatic.com/desktop2x/Chat~Governance~Reddit.f5769ee3503ebea4e475.js (1)
Running RtingsCrawler
Running ReferenceAudioAnalyzerCrawler
[0330/194954.684:INFO:CONSOLE(214)] "::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.", source: https://reference-audio-analyzer.pro/en/catalog-reports.php?sp_1=1&tp=1 (214)
[0330/194954.876:INFO:CONSOLE(651)] "Uncaught TypeError: Cannot read property 'addEventListener' of null", source: https://reference-audio-analyzer.pro/en/catalog-reports.php?sp_1=1&tp=1 (651)
[0330/194954.880:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/catalog-reports.php?sp_1=1&tp=1' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-left.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/catalog-reports.php?sp_1=1&tp=1 (0)
[0330/194954.881:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/catalog-reports.php?sp_1=1&tp=1' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-right.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/catalog-reports.php?sp_1=1&tp=1 (0)
"Apple Fake AirPods Pro Fake" is not known. Add true name and form to name index and run again.
[0330/195011.054:INFO:CONSOLE(213)] "::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.", source: https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588 (213)
[0330/195011.140:INFO:CONSOLE(589)] "Uncaught TypeError: Cannot read property 'addEventListener' of null", source: https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588 (589)
[0330/195011.149:INFO:CONSOLE(820)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-left.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588 (820)
[0330/195011.149:INFO:CONSOLE(820)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-right.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588 (820)
Graph image for "Audeze LCD-2 Closed Back" could not be downloaded from "https://reference-audio-analyzer.pro/en/nopublish.php?nopublish=2588". Perhaps it hasn't been published yet.
"Bose Sport Earbuds" is not known. Add true name and form to name index and run again.
"Bose Noise Cancelling 700 UC" is not known. Add true name and form to name index and run again.
"Bose QuietComfort Earbuds" is not known. Add true name and form to name index and run again.
[0330/195016.133:INFO:CONSOLE(676)] "Uncaught TypeError: Cannot read property 'addEventListener' of null", source: https://reference-audio-analyzer.pro/en/title-report.php?id=2445 (676)
[0330/195016.216:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/title-report.php?id=2445' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-left.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/title-report.php?id=2445 (0)
[0330/195016.217:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/title-report.php?id=2445' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-right.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/title-report.php?id=2445 (0)
[0330/195020.886:INFO:CONSOLE(291)] "::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.", source: https://reference-audio-analyzer.pro/en/report/hp/bower-wilkins-pi4-low.php (291)
[0330/195025.488:INFO:CONSOLE(31037)] "Uncaught TypeError: Cannot read property 'addEventListener' of null", source: https://reference-audio-analyzer.pro/en/report/hp/bower-wilkins-pi4-low.php (31037)
[0330/195025.515:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/report/hp/bower-wilkins-pi4-low.php' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-left.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/report/hp/bower-wilkins-pi4-low.php (0)
[0330/195025.515:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://reference-audio-analyzer.pro/en/report/hp/bower-wilkins-pi4-low.php' was loaded over HTTPS, but requested an insecure element 'http://pvbk.spb.ru/inc/carousel/ant-files/ant-arrow-right.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html", source: https://reference-audio-analyzer.pro/en/report/hp/bower-wilkins-pi4-low.php (0)
Downloaded to "C:\AutoEQ\measurements\referenceaudioanalyzer\images\.png"
Processing failed for "Bowers & Wilkins PI4"
Traceback (most recent call last):
  File "C:\AutoEQ\measurements\update_measurements.py", line 72, in <module>
    main(**create_cli())
  File "C:\AutoEQ\measurements\update_measurements.py", line 48, in main
    crawler.process_new(prompt=prompt)
  File "C:\AutoEQ\measurements\crawler.py", line 275, in process_new
    raise err
  File "C:\AutoEQ\measurements\crawler.py", line 256, in process_new
    self.process(item, url)
  File "C:\AutoEQ\measurements\referenceaudioanalyzer\reference_audio_analyzer_crawler.py", line 226, in process
    fr, inspection = ReferenceAudioAnalyzerCrawler.parse_image(im, name)
  File "C:\AutoEQ\measurements\referenceaudioanalyzer\reference_audio_analyzer_crawler.py", line 133, in parse_image
    fr = FrequencyResponse(model, f, amplitude)
  File "C:\AutoEQ\frequency_response.py", line 46, in __init__
    raise TypeError('Name must not be a non-empty string.')
TypeError: Name must not be a non-empty string.` 

When try I move on to run update_indexes.py it finishes with rankings.md only showing oratory1990 data.

**Comment by jaakkopasanen** [comment]
I just reworked the crawlers completely. Checkout the latest master and read through the updated instructions in the `measurements/README.md`.

Also it sounds like you moved directly from updating measurements to updating indexes. You need to update results before you can generate result indexes, including ranking.
