### ISSUE TITLE
I cant run autoeq.py program

### ISSUE THREAD

**Issue by jubilat0r** [jaakkopasanen/AutoEq#286]
Hello , after following the installing instructions, when i try to run "python autoeq.py --help" im getting a import dll error.

**To Reproduce**
(venv) C:\AutoEq-1.2.4\AutoEq-1.2.4>python autoeq.py --help
Traceback (most recent call last):
  File "autoeq.py", line 12, in <module>
    from frequency_response import FrequencyResponse
  File "C:\AutoEq-1.2.4\AutoEq-1.2.4\frequency_response.py", line 9, in <module>
    from scipy.interpolate import InterpolatedUnivariateSpline
  File "C:\AutoEq-1.2.4\AutoEq-1.2.4\venv\lib\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
    from .interpolate import *
  File "C:\AutoEq-1.2.4\AutoEq-1.2.4\venv\lib\site-packages\scipy\interpolate\interpolate.py", line 15, in <module>
    import scipy.special as spec
  File "C:\AutoEq-1.2.4\AutoEq-1.2.4\venv\lib\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: No se puede encontrar el módulo especificado.
**Expected behavior**

**System:**
 - OS: Windows 10 20H2
 - Compilation : 19042.906

**Comment by jaakkopasanen** [comment]
Hi. Thanks for reporting. A little Googling indicates that you might be missing MKL: https://stackoverflow.com/a/45514120

This is a system specific problem and I've never encountered it myself so can't really test the solution out for you.

**Comment by jubilat0r** [comment]
Thanks for anwering, i finally made it work using miniconda 3.8 and changing in requeriments.txt tensorflow~=2.0.0 -> tensorflow~=2.2.0
