### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by code010101** [jaakkopasanen/AutoEq#333]
**Describe the bug**
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

**To Reproduce**
The error appears when I try to use "--fixed_band_eq" or "--parametric_eq", while everything seems to be ok with "--convolution_eq"

**Files**
Traceback (most recent call last):
  File "C:\Users\Stefano\AutoEq\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autoeq.py", line 313, in <module>
    batch_processing(**cli_args())
  File "autoeq.py", line 83, in batch_processing
    peq_filters, n_peq_filters, peq_max_gains, fbeq_filters, n_fbeq_filters, fbeq_max_gain = fr.process(
  File "C:\Users\Stefano\AutoEq\frequency_response.py", line 1893, in process
    fbeq_filters, n_fbeq_filters, fbeq_max_gains = self.optimize_fixed_band_eq(fc=fc, q=q, fs=fs)
  File "C:\Users\Stefano\AutoEq\frequency_response.py", line 658, in optimize_fixed_band_eq
    eq, rmse, fc, Q, gain, coeffs_a, coeffs_b = self.optimize_biquad_filters(
  File "C:\Users\Stefano\AutoEq\frequency_response.py", line 278, in optimize_biquad_filters
    import tensorflow.compat.v1 as tf
  File "C:\Users\Stefano\AutoEq\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Stefano\AutoEq\venv\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\Stefano\AutoEq\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Stefano\AutoEq\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**System:**
 - OS: Windows 10 - 64bit (last release)
 - Git ver. 2.32.0.2
 - Python 3.8.10 (64-bit)

**Comment by code010101** [comment]
I solved by myself, by googling around I found a suggestion to uninstall / reinstall tensorflow:
1) pip uninstall tensorflow   (this uninstalled tensorflow-2.4.3 ...) 
2) pip install tensorflow   (this installed tensorflow-2.6.0-cp38-cp38-win_amd64.whl and its dependencies)

Now AutoEQ works!

**Comment by jaakkopasanen** [comment]
Thanks for reporting and especially for following up and posting the resolution!
