### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by IDrinkLava** [jaakkopasanen/AutoEq#351]
Trying to confirm installation with python AutoEq.py --help just gets me this:

```
Traceback (most recent call last):
  File "C:\Users\HomePC\AutoEq\venv\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\HomePC\AutoEq\venv\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\HomePC\AutoEq\venv\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AutoEq.py", line 8, in <module>
    import numpy as np
  File "C:\Users\HomePC\AutoEq\venv\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\HomePC\AutoEq\venv\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Users\HomePC\AutoEq\venv\Scripts\python.exe"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by IDrinkLava** [comment]
Nope, I followed all the instructions exactly, installed every single dependency, and even updated the requirements and I still persistently get this error.

**Comment by IDrinkLava** [comment]
Solved the issue. I updated to the latest version of Git, deleted my old AutoEQ installation, reinstalled AutoEQ and it just...worked. I swear I did everything right the last two attempts down to Windows SSL, but okay.

**Comment by Aiki-bot51** [comment]
nice
