### ISSUE TITLE
fiio fh9 measured by crinacle, would have generated my self but having issue with soundfile module under python 3.10 on macbook m1

### ISSUE THREAD

**Issue by adrianpuiu** [jaakkopasanen/AutoEq#424]
please generate for fiio fh9, it was measured by crinacle and the graphs can be found here.  i am having issues generating them on my own cause im on macbook pro m1 and can't import the soundfile module , here's the error i'm getting in pycharm console. I'm attaching the graphs here.
![FH9-Red](https://user-images.githubusercontent.com/187078/155224108-0b05ae15-a179-4326-ac46-4cf2444a5087.jpeg)
![FH9-Black](https://user-images.githubusercontent.com/187078/155224115-5a81053d-9569-457b-9e9c-a01dd10f986d.jpeg)
![FH9-Green](https://user-images.githubusercontent.com/187078/155224119-caae9048-eb85-4595-957f-64c07973bf25.jpeg)

/Users/agp/Downloads/AutoEq-master/venv/bin/python /Users/agp/Downloads/AutoEq-master/autoeq.py --input_dir=in/ --output_dir=out/ --compensation=compensation/harman_in-ear_2019v2_wo_bass.csv --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --convolution_eq --bass_boost=1 --standardize_input
Traceback (most recent call last):
  File "/Users/agp/Downloads/AutoEq-master/venv/lib/python3.10/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/agp/Downloads/AutoEq-master/autoeq.py", line 6, in <module>
    import soundfile as sf
  File "/Users/agp/Downloads/AutoEq-master/venv/lib/python3.10/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/Users/agp/Downloads/AutoEq-master/venv/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/agp/Downloads/AutoEq-master/venv/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/agp/Downloads/AutoEq-master/venv/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/usr/lib/libsndfile.dylib' (no such file)

Process finished with exit code 1

**Comment by adrianpuiu** [comment]
problem solved. installed miniconda  installed py38,  activated the env, moved the files from auto-eq folder into the env, installed requirments, runned the script ok with no errors
