### ISSUE TITLE
Errors when trying to run autoeq.py

### ISSUE THREAD

**Issue by dende82** [jaakkopasanen/AutoEq#441]
Hello,

I installed everything according to the install guide. But when I run autoeq.py, I get those errors:

> (venv) C:\AutoEq-master>python autoeq.py --input_dir="mydata" --output_dir="my_results/Soundcore_Life_P3" --compensation="compensation/harman_in-ear_2019v2.csv" --equalize --parametric_eq --max_filters=15+5 --ten_band_eq --convolution_eq --standardize_input --fixed_band_eq --fc 100,200,400,800,1600,3200,6400,12800 --q=1.414214
> Traceback (most recent call last):
>   File "autoeq.py", line 313, in <module>
>     batch_processing(**cli_args())
>   File "autoeq.py", line 79, in batch_processing
>     fr.center()
>   File "C:\AutoEq-master\frequency_response.py", line 998, in center
>     interpolator = InterpolatedUnivariateSpline(np.log10(equal_energy_fr.frequency), equal_energy_fr.raw, k=1)
>   File "C:\AutoEq-master\venv\lib\site-packages\scipy\interpolate\fitpack2.py", line 620, in __init__
>     x, y, w, bbox, self.ext = self.validate_input(x, y, w, bbox, k, None,
>   File "C:\AutoEq-master\venv\lib\site-packages\scipy\interpolate\fitpack2.py", line 202, in validate_input
>     raise ValueError("x and y should have a same length")
> ValueError: x and y should have a same length

System is Windows 10, Python is 3.8.10 (also tried 3.8.6)

Those commands ran also without errors:

> (venv) C:\AutoEq-master>python -m pip install -U pip
> Requirement already satisfied: pip in c:\autoeq-master\venv\lib\site-packages (22.0.4)
> 
> (venv) C:\AutoEq-master>python -m pip install -U -r requirements.txt
> Requirement already satisfied: Pillow~=7.2.0 in c:\autoeq-master\venv\lib\site-packages (from -r requirements.txt (line 1)) (7.2.0)
> [...]
> Requirement already satisfied: oauthlib>=3.0.0 in c:\autoeq-master\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow~=2.4.0->-r requirements.txt (line 6)) (3.2.0)

Tried rebooting, re-installing everything but it still keeps getting those errors. I also tried just using less commands but it didn't help.

I hope you can help me.

**Comment by jaakkopasanen** [comment]
My guess would be the problem is with the input data. Could you share your measurement files with me so that I can try to reproduce?

**Comment by jaakkopasanen** [comment]
Closing due to lack of activity. Please reopen if this is still problem after checking the input data.
