### ISSUE TITLE
Doesnt work in any linecode (line code below) 

### ISSUE THREAD

**Issue by angelooo18** [jaakkopasanen/AutoEq#464]
C:\Users\Angelo\Desktop>cd AutoEq

C:\Users\Angelo\Desktop\AutoEq>venv\Scripts\activate.bat

(venv) C:\Users\Angelo\Desktop\AutoEq>
(venv) C:\Users\Angelo\Desktop\AutoEq>python autoeq.py --input_dir="measurements/oratory1990/data/onear" --output_dir="my_results/oratory1990/harman_over-ear_2018" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4.0 --convolution_eq --fs=44100,48000
Traceback (most recent call last):
  File "autoeq.py", line 313, in <module>
    batch_processing(**cli_args())
  File "autoeq.py", line 83, in batch_processing
    peq_filters, n_peq_filters, peq_max_gains, fbeq_filters, n_fbeq_filters, fbeq_max_gain = fr.process(
  File "C:\Users\Angelo\Desktop\AutoEq\frequency_response.py", line 1887, in process
    peq_filters, n_peq_filters, peq_max_gains = self.optimize_parametric_eq(max_filters=max_filters, fs=fs)
  File "C:\Users\Angelo\Desktop\AutoEq\frequency_response.py", line 622, in optimize_parametric_eq
    _eq, rmse, _fc, _Q, _gain, _coeffs_a, _coeffs_b = self.optimize_biquad_filters(
  File "C:\Users\Angelo\Desktop\AutoEq\frequency_response.py", line 274, in optimize_biquad_filters
    import tensorflow.compat.v1 as tf
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\python\__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\Angelo\Desktop\AutoEq\venv\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

(venv) C:\Users\Angelo\Desktop\AutoEq>

I have pytthon 3.8.8, all the requirements installed

**Comment by angelooo18** [comment]
SOLVED using this linecode:
pip install --upgrade "protobuf<=3.20.1"
pip install 'protobuf<=3.20.1' --force-reinstall (if you can force it)

and change it to:
pip install tensorflow==2.9.1

all using venv

**Comment by jaakkopasanen** [comment]
This is probably solved now as Tensorflow is no longer a dependency. @angelooo18 can you confirm with freshly created virtualenv?
