### ISSUE TITLE
Can't reproduce any new parametric equalization. ValueError

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#527]
Any time I want to reproduce a parametric equalization with the new peq I get the same error:

<code>python autoeq.py --input_dir="measurements/oratory1990/data/onear" --output_dir="my_results/oratory1990/harman_over-ear_2018" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --equalize --parametric_eq --parametric_eq_config=8_PEAKING_WITH_SHELVES --ten_band_eq --bass_boost=4.0 --convolution_eq --fs=44100,48000

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/xxx/git/AutoEq/autoeq.py", line 116, in process_file_wrapper
    return process_file(*params)
  File "/home/xxx/git/AutoEq/autoeq.py", line 220, in process_file
    fr.write_readme(
  File "/home/xxx/git/AutoEq/frequency_response.py", line 474, in write_readme
    compound.add_filter(filt)
  File "/home/xxx/git/AutoEq/peq.py", line 495, in add_filter
    raise ValueError('Filter frequency array (f) must match equalizer frequency array')
ValueError: Filter frequency array (f) must match equalizer frequency array
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxx/git/AutoEq/autoeq.py", line 400, in <module>
    batch_processing(**cli_args())
  File "/home/xxx/git/AutoEq/autoeq.py", line 109, in batch_processing
    for result in tqdm.tqdm(
  File "/usr/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: Filter frequency array (f) must match equalizer frequency array`</code>

I am using Archlinux with the python packages from the arch repo. Versions are:

- python 3.10.7-1
- python-pillow 9.2.0-1
- python-matplotlib 3.5.2-1
- python-pandas 1.4.4-1
- python-scipy 1.9.1-1
- python-numpy 1.23.3-1
- python-tabulate 0.8.10-1
- python-soundfile 0.10.3.post1-3
- python-yaml 6.0-1
- python-tqdm 4.64.1-1

**Comment by jaakkopasanen** [comment]
Thanks for reporting this bug!

It should be fixed now. Can you plese confirm and close the ticket if the issue is solved.

**Comment by eduardoeae** [comment]
Fixed! Thanks
