### ISSUE TITLE
No module named 'soundfile'

### ISSUE THREAD

**Issue by francetrois242** [jaakkopasanen/AutoEq#604]
Hi, when running I get the soundfile error. I tried to install libsndfile but still not working. Here is the full error.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Git\AutoEq\autoeq\__main__.py", line 10, in <module>
    from autoeq.batch_processing import batch_processing
  File "C:\Program Files\Git\AutoEq\autoeq\batch_processing.py", line 6, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'

**Comment by CZTeo** [comment]
Hi,you closed the issue,have u found the solution to this?If so can you share it because I'm having the same issue.

**Comment by francetrois242** [comment]
Yes, look it up on google, you need to install it with command line. You will be missing other modules too, and will need to install these modules as well 1 by 1
