### ISSUE TITLE
Can't reproduce the result from self generated measurement

### ISSUE THREAD

**Issue by alazkaaa** [jaakkopasanen/AutoEq#624]
First of all, I don't know if this issue caused by me or not but everytime I generate the result, it always shows me this output:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\alazkaaa\git\AutoEQ\autoeq\__main__.py", line 209, in <module>
    batch_processing(**cli_args())
  File "C:\Users\alazkaaa\git\AutoEQ\autoeq\batch_processing.py", line 112, in batch_processing
    for result in tqdm.tqdm(
  File "C:\Users\alazkaaa\AppData\Roaming\Python\Python310\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 873, in next
    raise value
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 8, saw 3

The measurement was taken from rtings for my laptop's speaker. Thanks.

**Comment by jaakkopasanen** [comment]
Python 3.10 is not supported. Please downgrade to 3.9 and try again. Let me know if it works!

**Comment by jaakkopasanen** [comment]
Actually python 3.10 should work now since Docker build uses that. Probably didn't work in March.
