### ISSUE TITLE
ValueError: Duplicate values found at frequency 37. Remove duplicates manually.

### ISSUE THREAD

**Issue by Gabsan99** [jaakkopasanen/AutoEq#630]
Hello, I followed the guide to run AutoEQ on headphones that haven't been measured by any of the AutoEQ sources (FiiO FD3) and after trying to run AutoEQ I ran into the error stated in the title, I checked my CSV file and there doesn't seem to be any duplicate value. Is there something I am missing? Thanks in advance
Here is the CSV file:
[FiiO FD3.csv](https://github.com/jaakkopasanen/AutoEq/files/11162216/FiiO.FD3.csv)
And the output I get:
❯ python -m autoeq --input-dir="my_data/FiiO FD3" --output-dir="my_results/FiiO FD3" --compensation="compensation/oratory1990_wo_bass.csv" --parametric-eq --ten-band-eq --convolution-eq
  0%|                                                                                            | 0/2 [00:01<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\batch_processing.py", line 119, in process_file_wrapper
    return process_file(*params)
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\batch_processing.py", line 135, in process_file
    fr = FrequencyResponse.read_from_csv(input_file_path)
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\frequency_response.py", line 191, in read_from_csv
    return cls(
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\frequency_response.py", line 67, in __init__
    self._sort()
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\frequency_response.py", line 104, in _sort
    raise ValueError('Duplicate values found at frequency {}. Remove duplicates manually.'.format(
ValueError: Duplicate values found at frequency 37. Remove duplicates manually.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files (x86)\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\__main__.py", line 209, in <module>
    batch_processing(**cli_args())
  File "C:\Users\gianl\Downloads\AutoEq-master\autoeq\batch_processing.py", line 112, in batch_processing
    for result in tqdm.tqdm(
  File "D:\Program Files (x86)\Python\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "D:\Program Files (x86)\Python\lib\multiprocessing\pool.py", line 870, in next
    raise value
ValueError: Duplicate values found at frequency 37. Remove duplicates manually.

**Comment by jaakkopasanen** [comment]
Your file use comma as both decimal point as well as column separator and therefore won't work. I admit that the error message is not very helpful in this case though.

Change decimal point to `.` and this should work as intended.
